
    Resources:
      AnushaVPC:
        Type: AWS::EC2::VPC
        Properties:
          CidrBlock: 10.0.0.0/16
          Tags:
          - Key: Name
            Value:  !Join ['', [!Ref "AWS::StackName", "-VPC" ]]

      AnushaPublicSubnet:
        Type: AWS::EC2::Subnet
        Properties:
          VpcId: !Ref AnushaVPC
          AvailabilityZone: !Select [ 0, !GetAZs ]
          CidrBlock: 10.0.0.0/25
          MapPublicIpOnLaunch: true
          Tags:
          - Key: Name
            Value: !Sub ${AWS::StackName}-Public

      AnushaPrivateSubnet:
        Type: AWS::EC2::Subnet
        Properties:
          VpcId: !Ref AnushaVPC
          AvailabilityZone: !Select [ 1, !GetAZs ]
          CidrBlock: 10.0.0.128/25
          MapPublicIpOnLaunch: false
          Tags:
          - Key: Name
            Value: !Sub ${AWS::StackName}-Private

      AnushaIG:
        Type: AWS::EC2::InternetGateway
        Properties:
          Tags:
          - Key: Name
            Value: !Join [_, [!Ref 'AWS::StackName']]

      GatewayToInternet:
        Type: AWS::EC2::VPCGatewayAttachment
        Properties:
          VpcId: !Ref AnushaVPC
          InternetGatewayId: !Ref AnushaIG

      PublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
          VpcId: !Ref AnushaVPC
          Tags:
          - Key: Name
            Value: Public

      PublicRoute:
        Type: AWS::EC2::Route
        DependsOn: GatewayToInternet
        Properties:
          RouteTableId: !Ref PublicRouteTable
          DestinationCidrBlock: 0.0.0.0/0
          GatewayId: !Ref AnushaIG

      PublicSubnetRouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
          SubnetId: !Ref AnushaPublicSubnet
          RouteTableId: !Ref PublicRouteTable

      NatGateway:
        Type: AWS::EC2::NatGateway
        DependsOn: NatPublicIP
        Properties:
          AllocationId: !GetAtt NatPublicIP.AllocationId
          SubnetId: !Ref AnushaPublicSubnet
          Tags:
          - Key: Name
            Value: !Sub NAT-${AWS::StackName}

      NatPublicIP:
        Type: AWS::EC2::EIP
        DependsOn: AnushaVPC
        Properties:
          Domain: vpc

      PrivateRouteTable:
        Type: AWS::EC2::RouteTable
        Properties:
          VpcId: !Ref AnushaVPC
          Tags:
          - Key: Name
            Value: Private

      PrivateRoute:
        Type: AWS::EC2::Route
        Properties:
          RouteTableId: !Ref PrivateRouteTable
          DestinationCidrBlock: 0.0.0.0/0
          NatGatewayId: !Ref NatGateway

      PrivateSubnetRouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
          SubnetId: !Ref AnushaPrivateSubnet
          RouteTableId: !Ref PrivateRouteTable
