---
- hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Provision instance
      ec2:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        key_name: Mylinux
        instance_type: t2.micro
        image: ami-0761dd91277e34178
        wait: yes
        count: 1
        region: us-east-1

